# Generated by Django 5.2.1 on 2025-07-08 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Book', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ename', models.CharField(max_length=20)),
                ('sal', models.FloatField()),
                ('deptno', models.IntegerField()),
                ('job', models.CharField(max_length=20)),
                ('age', models.IntegerField()),
            ],
        ),
    ]
